[properties]
boxed = [
    [
        "../../vsts-rest-api-specs.patched/specification/build/7.1/build.json",
        "Build",
        "triggeredByBuild",
    ],
    [
        "../../vsts-rest-api-specs.patched/specification/distributedTask/7.1/taskAgent.json",
        "TaskOrchestrationContainer",
        "rollback",
    ],
    [
        "../../vsts-rest-api-specs.patched/specification/distributedTask/7.1/taskAgent.json",
        "JToken",
        "first",
    ],
    [
        "../../vsts-rest-api-specs.patched/specification/distributedTask/7.1/taskAgent.json",
        "JToken",
        "item",
    ],
    [
        "../../vsts-rest-api-specs.patched/specification/distributedTask/7.1/taskAgent.json",
        "JToken",
        "last",
    ],
    [
        "../../vsts-rest-api-specs.patched/specification/distributedTask/7.1/taskAgent.json",
        "JToken",
        "next",
    ],
    [
        "../../vsts-rest-api-specs.patched/specification/distributedTask/7.1/taskAgent.json",
        "JToken",
        "previous",
    ],
    [
        "../../vsts-rest-api-specs.patched/specification/distributedTask/7.1/taskAgent.json",
        "JToken",
        "root",
    ],
    [
        "../../vsts-rest-api-specs.patched/specification/graph/7.1/graph.json",
        "JToken",
        "first",
    ],
    [
        "../../vsts-rest-api-specs.patched/specification/graph/7.1/graph.json",
        "JToken",
        "item",
    ],
    [
        "../../vsts-rest-api-specs.patched/specification/graph/7.1/graph.json",
        "JToken",
        "last",
    ],
    [
        "../../vsts-rest-api-specs.patched/specification/graph/7.1/graph.json",
        "JToken",
        "next",
    ],
    [
        "../../vsts-rest-api-specs.patched/specification/graph/7.1/graph.json",
        "JToken",
        "previous",
    ],
    [
        "../../vsts-rest-api-specs.patched/specification/graph/7.1/graph.json",
        "JToken",
        "root",
    ],
    [
        "../../vsts-rest-api-specs.patched/specification/serviceEndpoint/7.1/serviceEndpoint.json",
        "JToken",
        "first",
    ],
    [
        "../../vsts-rest-api-specs.patched/specification/serviceEndpoint/7.1/serviceEndpoint.json",
        "JToken",
        "item",
    ],
    [
        "../../vsts-rest-api-specs.patched/specification/serviceEndpoint/7.1/serviceEndpoint.json",
        "JToken",
        "last",
    ],
    [
        "../../vsts-rest-api-specs.patched/specification/serviceEndpoint/7.1/serviceEndpoint.json",
        "JToken",
        "next",
    ],
    [
        "../../vsts-rest-api-specs.patched/specification/serviceEndpoint/7.1/serviceEndpoint.json",
        "JToken",
        "previous",
    ],
    [
        "../../vsts-rest-api-specs.patched/specification/serviceEndpoint/7.1/serviceEndpoint.json",
        "JToken",
        "root",
    ],
]
